org: ukstv
app: aws-node-http-api-project
service: aws-node-http-api-project
frameworkVersion: '3'

plugins:
  - serverless-esbuild
  - serverless-lift

custom:
  esbuild:
    minify: true
    watch:
      # anymatch-compatible definition (https://github.com/es128/anymatch)
      pattern: ['./index.ts', 'src/**/*.ts'] # default .
      ignore: ['.serverless/**/*', '.build'] # default ['.build', 'dist', 'node_modules']

provider:
  name: aws
  runtime: nodejs16.x
  timeout: 60
  memorySize: 2048

constructs:
  jobs:
    type: queue
    batchSize: 1
    worker:
      handler: src/handlers/consumer.consumer

functions:
  producer:
    handler: src/handlers/trigger.producer
    events:
      - httpApi:
          method: post
          path: /produce
    environment:
      QUEUE_URL: ${construct:jobs.queueUrl}
