service: ceramic-benchmark-01
frameworkVersion: '3'

plugins:
  - serverless-esbuild
  - serverless-lift

custom:
  esbuild:
    minify: true
    watch:
      # anymatch-compatible definition (https://github.com/es128/anymatch)
      pattern: ['./index.ts', 'src/**/*.ts'] # default .
      ignore: ['.serverless/**/*', '.build'] # default ['.build', 'dist', 'node_modules']

provider:
  name: aws
  iam:
    role:
      statements:
        - Effect: Allow
          Action: 'cloudwatch:PutMetricData'
          Resource: '*'
  runtime: nodejs16.x
  timeout: 120
  memorySize: 2048

constructs:
  jobs:
    type: queue
    batchSize: 10
    worker:
      handler: src/handlers/consumer.consumer
      timeout: 120
  multistream:
    type: queue
    batchSize: 10
    worker:
      handler: src/handlers/multistream.consumer
      timeout: 120
  composedb:
    type: queue
    batchSize: 10
    worker:
      handler: src/handlers/composedb.consumer
      timeout: 120

functions:
  producerMultistream:
    handler: src/handlers/multistream.trigger
    events:
      - httpApi:
          method: post
          path: /multistream
    environment:
      QUEUE_URL: ${construct:multistream.queueUrl}
  producer:
    handler: src/handlers/trigger.producer
    events:
      - httpApi:
          method: post
          path: /produce
    environment:
      QUEUE_URL: ${construct:jobs.queueUrl}
  composedbTrigger:
    handler: src/handlers/composedb.trigger
    events:
      - httpApi:
          method: post
          path: /composedbTrigger
    environment:
      QUEUE_URL: ${construct:composedb.queueUrl}
